import type { HeadlessLoginLabels } from "./HeadlessLoginPanel";

/** Locales shipped with the shared login card. Products may pass a wider menu. */
export type LoginLocale =
  | "zh-CN"
  | "zh-TW"
  | "ja"
  | "ko"
  | "en"
  | "pt"
  | "nl"
  | "it"
  | "es"
  | "fr";

export interface LoginLocaleOption {
  code: string;
  label: string;
  short: string;
}

/** Menu order: CJK and English first; long European names, then Spanish and French. */
export const DEFAULT_LOGIN_LOCALES: readonly LoginLocaleOption[] = [
  { code: "zh-CN", label: "简体中文", short: "简" },
  { code: "zh-TW", label: "繁體中文", short: "繁" },
  { code: "ja", label: "日本語", short: "JA" },
  { code: "ko", label: "한국어", short: "KO" },
  { code: "en", label: "English", short: "EN" },
  { code: "pt", label: "Português", short: "PT" },
  { code: "nl", label: "Nederlands", short: "NL" },
  { code: "it", label: "Italiano", short: "IT" },
  { code: "es", label: "Español", short: "ES" },
  { code: "fr", label: "Français", short: "FR" },
];

const ZH_CN: HeadlessLoginLabels = {
  title: "登录",
  subtitle: "使用 LuminaryWorks 统一账号",
  identifierPlaceholder: "邮箱或用户名",
  registerIdentifierPlaceholder: "用户名",
  passwordPlaceholder: "密码",
  confirmPasswordPlaceholder: "确认密码",
  submitPassword: "密码登录",
  submitRegister: "创建账号",
  submitSso: "使用统一账号继续",
  submitGoogle: "Google",
  submitGithub: "GitHub",
  socialDivider: "或",
  hint: "社交账号会直接打开对应服务。密码登录使用你的 LuminaryWorks 账号。",
  registerHint: "邮箱需要验证码；用户名与邮箱都要填写。",
  cancel: "取消",
  experienceUnavailable: "密码登录暂不可用，请改用社交账号。",
  showPassword: "显示密码",
  hidePassword: "隐藏密码",
  registerLink: "创建账号",
  loginLink: "已有账号？去登录",
  passwordMismatch: "两次密码不一致",
  registerTitle: "创建账号",
  registerSubtitle: "创建 LuminaryWorks 统一账号",
  registerWithEmail: "邮箱",
  registerWithUsername: "用户名",
  emailPlaceholder: "邮箱",
  verificationCodePlaceholder: "验证码",
  sendCode: "发送验证码",
  resendCode: "重新发送",
  allowedDomainsPrefix: "允许的邮箱域名",
  allowedDomainsOpen: "大多数邮箱都可以注册。",
  allowedDomainsBlocklist: "大多数邮箱可用。临时邮箱会被拒绝。",
  allowedDomainsInfo: "查看全部允许的邮箱域名",
  usernameInvalid: "用户名须以字母或下划线开头，只能包含字母、数字和下划线。",
  usernameTaken: "该用户名已被占用",
  emailInvalid: "请输入有效的邮箱地址",
  emailTaken: "该邮箱已注册",
  emailDomainNotAllowed: "该邮箱域名不允许自助注册",
  emailDisposable: "不支持临时或一次性邮箱",
  waitingExternalBrowser: "请在浏览器中完成登录，然后回到本应用。",
  consentRequired: "请先同意用户协议后再继续。",
  mfaTitle: "身份验证码",
  mfaSubtitle: "输入验证器应用中的 6 位数字。",
  mfaCodePlaceholder: "6 位验证码",
  mfaSubmit: "验证并继续",
  mfaBack: "返回",
};

const ZH_TW: HeadlessLoginLabels = {
  title: "登入",
  subtitle: "使用 LuminaryWorks 統一帳號",
  identifierPlaceholder: "電子郵件或使用者名稱",
  registerIdentifierPlaceholder: "使用者名稱",
  passwordPlaceholder: "密碼",
  confirmPasswordPlaceholder: "確認密碼",
  submitPassword: "密碼登入",
  submitRegister: "建立帳號",
  submitSso: "使用統一帳號繼續",
  submitGoogle: "Google",
  submitGithub: "GitHub",
  socialDivider: "或",
  hint: "社交帳號會直接開啟對應服務。密碼登入使用你的 LuminaryWorks 帳號。",
  registerHint: "電子郵件需要驗證碼；使用者名稱與電子郵件都要填寫。",
  cancel: "取消",
  experienceUnavailable: "密碼登入暫不可用，請改用社交帳號。",
  showPassword: "顯示密碼",
  hidePassword: "隱藏密碼",
  registerLink: "建立帳號",
  loginLink: "已有帳號？去登入",
  passwordMismatch: "兩次密碼不一致",
  registerTitle: "建立帳號",
  registerSubtitle: "建立 LuminaryWorks 統一帳號",
  registerWithEmail: "電子郵件",
  registerWithUsername: "使用者名稱",
  emailPlaceholder: "電子郵件",
  verificationCodePlaceholder: "驗證碼",
  sendCode: "發送驗證碼",
  resendCode: "重新發送",
  allowedDomainsPrefix: "允許的電子郵件網域",
  allowedDomainsOpen: "大多數電子郵件都可以註冊。",
  allowedDomainsBlocklist: "大多數電子郵件可用。臨時信箱會被拒絕。",
  allowedDomainsInfo: "查看全部允許的電子郵件網域",
  usernameInvalid: "使用者名稱須以字母或底線開頭，只能包含字母、數字與底線。",
  usernameTaken: "此使用者名稱已被使用",
  emailInvalid: "請輸入有效的電子郵件",
  emailTaken: "此電子郵件已註冊",
  emailDomainNotAllowed: "此電子郵件網域不允許自助註冊",
  emailDisposable: "不支援臨時或一次性電子郵件",
  waitingExternalBrowser: "請在瀏覽器中完成登入，然後回到本應用。",
  consentRequired: "請先同意使用條款後再繼續。",
  mfaTitle: "身分驗證碼",
  mfaSubtitle: "輸入驗證器應用程式中的 6 位數字。",
  mfaCodePlaceholder: "6 位驗證碼",
  mfaSubmit: "驗證並繼續",
  mfaBack: "返回",
};

const ES: HeadlessLoginLabels = {
  title: "Iniciar sesión",
  subtitle: "Usa tu cuenta unificada de LuminaryWorks",
  identifierPlaceholder: "Correo o usuario",
  registerIdentifierPlaceholder: "Usuario",
  passwordPlaceholder: "Contraseña",
  confirmPasswordPlaceholder: "Confirmar contraseña",
  submitPassword: "Entrar con contraseña",
  submitRegister: "Crear cuenta",
  submitSso: "Continuar con la cuenta unificada",
  submitGoogle: "Google",
  submitGithub: "GitHub",
  socialDivider: "o",
  hint: "Las redes abren el proveedor directamente. La contraseña usa tu cuenta LuminaryWorks.",
  registerHint: "El correo necesita un código. El usuario y el correo son obligatorios.",
  cancel: "Cancelar",
  experienceUnavailable: "El inicio con contraseña no está disponible. Usa una red social.",
  showPassword: "Mostrar contraseña",
  hidePassword: "Ocultar contraseña",
  registerLink: "Crear una cuenta",
  loginLink: "¿Ya tienes cuenta? Inicia sesión",
  passwordMismatch: "Las contraseñas no coinciden",
  registerTitle: "Crear cuenta",
  registerSubtitle: "Crea tu cuenta unificada de LuminaryWorks",
  registerWithEmail: "Correo",
  registerWithUsername: "Usuario",
  emailPlaceholder: "Correo",
  verificationCodePlaceholder: "Código",
  sendCode: "Enviar código",
  resendCode: "Reenviar",
  allowedDomainsPrefix: "Dominios de correo permitidos",
  allowedDomainsOpen: "El registro por correo está abierto para la mayoría de proveedores.",
  allowedDomainsBlocklist: "Se aceptan la mayoría de correos. Se bloquean direcciones temporales.",
  allowedDomainsInfo: "Ver todos los dominios de correo permitidos",
  usernameInvalid:
    "El usuario debe empezar por una letra o _ y usar solo letras, dígitos y _.",
  usernameTaken: "Este usuario ya está en uso",
  emailInvalid: "Introduce un correo válido",
  emailTaken: "Este correo ya está registrado",
  emailDomainNotAllowed: "Este dominio de correo no está permitido para el registro",
  emailDisposable: "No se permiten correos temporales o desechables",
  waitingExternalBrowser: "Termina el inicio de sesión en el navegador y vuelve a esta app.",
  consentRequired: "Acepta los términos antes de continuar.",
};

const JA: HeadlessLoginLabels = {
  title: "ログイン",
  subtitle: "LuminaryWorks 統合アカウントを使用",
  identifierPlaceholder: "メールまたはユーザー名",
  registerIdentifierPlaceholder: "ユーザー名",
  passwordPlaceholder: "パスワード",
  confirmPasswordPlaceholder: "パスワード確認",
  submitPassword: "パスワードでログイン",
  submitRegister: "アカウント作成",
  submitSso: "統合アカウントで続ける",
  submitGoogle: "Google",
  submitGithub: "GitHub",
  socialDivider: "または",
  hint: "ソーシャルは各サービスを直接開きます。パスワードは LuminaryWorks アカウントです。",
  registerHint: "メールには確認コードが必要です。ユーザー名とメールの両方が必要です。",
  cancel: "キャンセル",
  experienceUnavailable: "パスワードログインは使えません。ソーシャルをお使いください。",
  showPassword: "パスワードを表示",
  hidePassword: "パスワードを隠す",
  registerLink: "アカウントを作成",
  loginLink: "アカウントをお持ちですか？ログイン",
  passwordMismatch: "パスワードが一致しません",
  registerTitle: "アカウント作成",
  registerSubtitle: "LuminaryWorks 統合アカウントを作成",
  registerWithEmail: "メール",
  registerWithUsername: "ユーザー名",
  emailPlaceholder: "メール",
  verificationCodePlaceholder: "確認コード",
  sendCode: "コードを送信",
  resendCode: "再送信",
  allowedDomainsPrefix: "利用できるメールドメイン",
  allowedDomainsOpen: "ほとんどのメールで登録できます。",
  allowedDomainsBlocklist: "ほとんどのメールは使えます。使い捨てアドレスは拒否されます。",
  allowedDomainsInfo: "利用できるメールドメインをすべて表示",
  usernameInvalid: "ユーザー名は英字または _ で始め、英数字と _ のみ使用できます。",
  usernameTaken: "このユーザー名は既に使われています",
  emailInvalid: "有効なメールアドレスを入力してください",
  emailTaken: "このメールは既に登録されています",
  emailDomainNotAllowed: "このメールドメインでは自己登録できません",
  emailDisposable: "一時的または使い捨てメールは使えません",
  waitingExternalBrowser: "ブラウザでログインを終えたら、このアプリに戻ってください。",
  consentRequired: "続ける前に利用規約へ同意してください。",
};

const KO: HeadlessLoginLabels = {
  title: "로그인",
  subtitle: "LuminaryWorks 통합 계정 사용",
  identifierPlaceholder: "이메일 또는 사용자 이름",
  registerIdentifierPlaceholder: "사용자 이름",
  passwordPlaceholder: "비밀번호",
  confirmPasswordPlaceholder: "비밀번호 확인",
  submitPassword: "비밀번호로 로그인",
  submitRegister: "계정 만들기",
  submitSso: "통합 계정으로 계속",
  submitGoogle: "Google",
  submitGithub: "GitHub",
  socialDivider: "또는",
  hint: "소셜 로그인은 해당 서비스를 바로 엽니다. 비밀번호는 LuminaryWorks 계정입니다.",
  registerHint: "이메일에는 인증 코드가 필요합니다. 사용자 이름과 이메일을 모두 입력하세요.",
  cancel: "취소",
  experienceUnavailable: "비밀번호 로그인을 사용할 수 없습니다. 소셜 로그인을 사용하세요.",
  showPassword: "비밀번호 표시",
  hidePassword: "비밀번호 숨기기",
  registerLink: "계정 만들기",
  loginLink: "계정이 있나요? 로그인",
  passwordMismatch: "비밀번호가 일치하지 않습니다",
  registerTitle: "계정 만들기",
  registerSubtitle: "LuminaryWorks 통합 계정 만들기",
  registerWithEmail: "이메일",
  registerWithUsername: "사용자 이름",
  emailPlaceholder: "이메일",
  verificationCodePlaceholder: "인증 코드",
  sendCode: "코드 보내기",
  resendCode: "다시 보내기",
  allowedDomainsPrefix: "허용된 이메일 도메인",
  allowedDomainsOpen: "대부분의 이메일로 가입할 수 있습니다.",
  allowedDomainsBlocklist: "대부분의 이메일을 허용합니다. 임시 주소는 거부됩니다.",
  allowedDomainsInfo: "허용된 이메일 도메인 전체 보기",
  usernameInvalid: "사용자 이름은 영문 또는 _로 시작하고 영문, 숫자, _만 사용할 수 있습니다.",
  usernameTaken: "이미 사용 중인 사용자 이름입니다",
  emailInvalid: "유효한 이메일을 입력하세요",
  emailTaken: "이미 등록된 이메일입니다",
  emailDomainNotAllowed: "이 이메일 도메인은 가입에 사용할 수 없습니다",
  emailDisposable: "임시 또는 일회용 이메일은 사용할 수 없습니다",
  waitingExternalBrowser: "브라우저에서 로그인을 마친 뒤 이 앱으로 돌아오세요.",
  consentRequired: "계속하려면 약관에 동의하세요.",
};

const PT: HeadlessLoginLabels = {
  title: "Entrar",
  subtitle: "Use a conta unificada LuminaryWorks",
  identifierPlaceholder: "E-mail ou usuário",
  registerIdentifierPlaceholder: "Usuário",
  passwordPlaceholder: "Senha",
  confirmPasswordPlaceholder: "Confirmar senha",
  submitPassword: "Entrar com senha",
  submitRegister: "Criar conta",
  submitSso: "Continuar com a conta unificada",
  submitGoogle: "Google",
  submitGithub: "GitHub",
  socialDivider: "ou",
  hint: "Redes sociais abrem o provedor direto. A senha usa sua conta LuminaryWorks.",
  registerHint: "O e-mail precisa de um código. Usuário e e-mail são obrigatórios.",
  cancel: "Cancelar",
  experienceUnavailable: "Entrada por senha indisponível. Use uma rede social.",
  showPassword: "Mostrar senha",
  hidePassword: "Ocultar senha",
  registerLink: "Criar uma conta",
  loginLink: "Já tem conta? Entrar",
  passwordMismatch: "As senhas não coincidem",
  registerTitle: "Criar conta",
  registerSubtitle: "Crie sua conta unificada LuminaryWorks",
  registerWithEmail: "E-mail",
  registerWithUsername: "Usuário",
  emailPlaceholder: "E-mail",
  verificationCodePlaceholder: "Código",
  sendCode: "Enviar código",
  resendCode: "Reenviar",
  allowedDomainsPrefix: "Domínios de e-mail permitidos",
  allowedDomainsOpen: "O cadastro por e-mail está aberto para a maioria dos provedores.",
  allowedDomainsBlocklist: "A maioria dos e-mails é aceita. Endereços temporários são bloqueados.",
  allowedDomainsInfo: "Ver todos os domínios de e-mail permitidos",
  usernameInvalid: "O usuário deve começar com letra ou _ e usar só letras, dígitos e _.",
  usernameTaken: "Este usuário já está em uso",
  emailInvalid: "Informe um e-mail válido",
  emailTaken: "Este e-mail já está cadastrado",
  emailDomainNotAllowed: "Este domínio de e-mail não é permitido no cadastro",
  emailDisposable: "E-mails temporários ou descartáveis não são permitidos",
  waitingExternalBrowser: "Conclua o login no navegador e volte a este app.",
  consentRequired: "Aceite os termos antes de continuar.",
};

const NL: HeadlessLoginLabels = {
  title: "Inloggen",
  subtitle: "Gebruik je LuminaryWorks-account",
  identifierPlaceholder: "E-mail of gebruikersnaam",
  registerIdentifierPlaceholder: "Gebruikersnaam",
  passwordPlaceholder: "Wachtwoord",
  confirmPasswordPlaceholder: "Bevestig wachtwoord",
  submitPassword: "Inloggen met wachtwoord",
  submitRegister: "Account maken",
  submitSso: "Doorgaan met unified account",
  submitGoogle: "Google",
  submitGithub: "GitHub",
  socialDivider: "of",
  hint: "Sociale logins openen de provider direct. Het wachtwoord is je LuminaryWorks-account.",
  registerHint: "E-mail heeft een code nodig. Gebruikersnaam en e-mail zijn beide verplicht.",
  cancel: "Annuleren",
  experienceUnavailable: "Inloggen met wachtwoord is niet beschikbaar. Gebruik een sociale login.",
  showPassword: "Wachtwoord tonen",
  hidePassword: "Wachtwoord verbergen",
  registerLink: "Account maken",
  loginLink: "Al een account? Inloggen",
  passwordMismatch: "Wachtwoorden komen niet overeen",
  registerTitle: "Account maken",
  registerSubtitle: "Maak je LuminaryWorks-account",
  registerWithEmail: "E-mail",
  registerWithUsername: "Gebruikersnaam",
  emailPlaceholder: "E-mail",
  verificationCodePlaceholder: "Code",
  sendCode: "Code versturen",
  resendCode: "Opnieuw",
  allowedDomainsPrefix: "Toegestane e-maildomeinen",
  allowedDomainsOpen: "Registreren kan met de meeste e-mailproviders.",
  allowedDomainsBlocklist: "De meeste adressen zijn toegestaan. Tijdelijke adressen worden geweigerd.",
  allowedDomainsInfo: "Alle toegestane e-maildomeinen tonen",
  usernameInvalid: "Gebruikersnaam begint met een letter of _ en gebruikt alleen letters, cijfers en _.",
  usernameTaken: "Deze gebruikersnaam is al in gebruik",
  emailInvalid: "Vul een geldig e-mailadres in",
  emailTaken: "Dit e-mailadres is al geregistreerd",
  emailDomainNotAllowed: "Dit e-maildomein is niet toegestaan voor registratie",
  emailDisposable: "Tijdelijke of wegwerp-e-mailadressen zijn niet toegestaan",
  waitingExternalBrowser: "Rond het inloggen af in de browser en kom terug naar deze app.",
  consentRequired: "Ga eerst akkoord met de voorwaarden.",
};

const IT: HeadlessLoginLabels = {
  title: "Accedi",
  subtitle: "Usa l'account unificato LuminaryWorks",
  identifierPlaceholder: "Email o nome utente",
  registerIdentifierPlaceholder: "Nome utente",
  passwordPlaceholder: "Password",
  confirmPasswordPlaceholder: "Conferma password",
  submitPassword: "Accedi con password",
  submitRegister: "Crea account",
  submitSso: "Continua con l'account unificato",
  submitGoogle: "Google",
  submitGithub: "GitHub",
  socialDivider: "oppure",
  hint: "I social aprono il provider. La password usa il tuo account LuminaryWorks.",
  registerHint: "L'email richiede un codice. Nome utente ed email sono entrambi obbligatori.",
  cancel: "Annulla",
  experienceUnavailable: "Accesso con password non disponibile. Usa un social.",
  showPassword: "Mostra password",
  hidePassword: "Nascondi password",
  registerLink: "Crea un account",
  loginLink: "Hai già un account? Accedi",
  passwordMismatch: "Le password non coincidono",
  registerTitle: "Crea account",
  registerSubtitle: "Crea il tuo account unificato LuminaryWorks",
  registerWithEmail: "Email",
  registerWithUsername: "Nome utente",
  emailPlaceholder: "Email",
  verificationCodePlaceholder: "Codice",
  sendCode: "Invia codice",
  resendCode: "Invia di nuovo",
  allowedDomainsPrefix: "Domini email consentiti",
  allowedDomainsOpen: "La registrazione email è aperta per la maggior parte dei provider.",
  allowedDomainsBlocklist: "La maggior parte delle email è accettata. Gli indirizzi temporanei sono bloccati.",
  allowedDomainsInfo: "Mostra tutti i domini email consentiti",
  usernameInvalid: "Il nome utente inizia con una lettera o _ e usa solo lettere, cifre e _.",
  usernameTaken: "Questo nome utente è già in uso",
  emailInvalid: "Inserisci un'email valida",
  emailTaken: "Questa email è già registrata",
  emailDomainNotAllowed: "Questo dominio email non è consentito per la registrazione",
  emailDisposable: "Gli indirizzi email temporanei o usa e getta non sono consentiti",
  waitingExternalBrowser: "Completa l'accesso nel browser e torna a questa app.",
  consentRequired: "Accetta i termini prima di continuare.",
};

const FR: HeadlessLoginLabels = {
  title: "Connexion",
  subtitle: "Utilisez votre compte unifié LuminaryWorks",
  identifierPlaceholder: "E-mail ou nom d'utilisateur",
  registerIdentifierPlaceholder: "Nom d'utilisateur",
  passwordPlaceholder: "Mot de passe",
  confirmPasswordPlaceholder: "Confirmer le mot de passe",
  submitPassword: "Se connecter avec mot de passe",
  submitRegister: "Créer un compte",
  submitSso: "Continuer avec le compte unifié",
  submitGoogle: "Google",
  submitGithub: "GitHub",
  socialDivider: "ou",
  hint: "Les réseaux ouvrent le fournisseur. Le mot de passe utilise votre compte LuminaryWorks.",
  registerHint: "L'e-mail nécessite un code. Le nom d'utilisateur et l'e-mail sont tous deux requis.",
  cancel: "Annuler",
  experienceUnavailable: "Connexion par mot de passe indisponible. Utilisez un réseau social.",
  showPassword: "Afficher le mot de passe",
  hidePassword: "Masquer le mot de passe",
  registerLink: "Créer un compte",
  loginLink: "Déjà un compte ? Se connecter",
  passwordMismatch: "Les mots de passe ne correspondent pas",
  registerTitle: "Créer un compte",
  registerSubtitle: "Créez votre compte unifié LuminaryWorks",
  registerWithEmail: "E-mail",
  registerWithUsername: "Nom d'utilisateur",
  emailPlaceholder: "E-mail",
  verificationCodePlaceholder: "Code",
  sendCode: "Envoyer le code",
  resendCode: "Renvoyer",
  allowedDomainsPrefix: "Domaines e-mail autorisés",
  allowedDomainsOpen: "L'inscription par e-mail est ouverte pour la plupart des fournisseurs.",
  allowedDomainsBlocklist: "La plupart des e-mails sont acceptés. Les adresses jetables sont refusées.",
  allowedDomainsInfo: "Afficher tous les domaines e-mail autorisés",
  usernameInvalid:
    "Le nom d'utilisateur commence par une lettre ou _ et n'utilise que lettres, chiffres et _.",
  usernameTaken: "Ce nom d'utilisateur est déjà pris",
  emailInvalid: "Saisissez une adresse e-mail valide",
  emailTaken: "Cet e-mail est déjà enregistré",
  emailDomainNotAllowed: "Ce domaine e-mail n'est pas autorisé pour l'inscription",
  emailDisposable: "Les adresses e-mail temporaires ou jetables ne sont pas autorisées",
  waitingExternalBrowser: "Terminez la connexion dans le navigateur, puis revenez à cette application.",
  consentRequired: "Acceptez les conditions avant de continuer.",
  mfaTitle: "Code d'authentification",
  mfaSubtitle: "Saisissez le code à 6 chiffres de votre application.",
  mfaCodePlaceholder: "123456",
  mfaSubmit: "Vérifier et continuer",
  mfaBack: "Retour",
};

const BY_LOCALE: Record<LoginLocale, HeadlessLoginLabels | undefined> = {
  en: undefined,
  "zh-CN": ZH_CN,
  "zh-TW": ZH_TW,
  ja: JA,
  ko: KO,
  pt: PT,
  nl: NL,
  it: IT,
  es: ES,
  fr: FR,
};

/** Normalize product locale tags (`zh`, `zh-Hans`) onto the card dictionary. */
export function normalizeLoginLocale(locale: string | undefined): LoginLocale {
  const raw = (locale ?? "en").trim().toLowerCase();
  if (raw === "zh" || raw === "zh-cn" || raw === "zh-hans" || raw.startsWith("zh-cn")) {
    return "zh-CN";
  }
  if (raw === "zh-tw" || raw === "zh-hant" || raw.startsWith("zh-tw") || raw.startsWith("zh-hk")) {
    return "zh-TW";
  }
  if (raw === "ja" || raw.startsWith("ja-")) return "ja";
  if (raw === "ko" || raw.startsWith("ko-")) return "ko";
  if (raw === "pt" || raw.startsWith("pt-")) return "pt";
  if (raw === "nl" || raw.startsWith("nl-")) return "nl";
  if (raw === "it" || raw.startsWith("it-")) return "it";
  if (raw === "es" || raw.startsWith("es-")) return "es";
  if (raw === "fr" || raw.startsWith("fr-")) return "fr";
  if (raw === "en" || raw.startsWith("en-")) return "en";
  return "en";
}

/** Card copy for a locale. English is the panel default, so `en` returns `{}`. */
export function loginLabels(locale: string | undefined): HeadlessLoginLabels {
  return BY_LOCALE[normalizeLoginLocale(locale)] ?? {};
}
